### PR TITLE
Fix bug when used with descending order

### PR DESCRIPTION
**Pull request by zakdoek**
Bugfix

### CODE REVIEW

**Comment by alsoicode** [comment]
Nice catch, thanks. I need to revamp testing for this app.

**Comment by alsoicode** [comment]
I'll get a release out on PyPi shortly.

**Comment by zakdoek** [comment]
Thx for the quick response.

**Comment by alsoicode** [comment]
You're welcome. Thanks again for the bugfix. I've pushed 2.0.3 out to PyPi.

**Pull request merged**
