### PR TITLE
Remove fallbacks for Django < 1.8

### PR DESCRIPTION
**Pull request by jaap3**
* Add tox.ini to test and generate a coverage report over a range of Python and Django versions
* Remove multiple fallbacks and conditionals that are no longer needed
* Remove South support
* Update sample_project to be future compatible (up to Django 2.0)
* Update tests to be future compatible

I've tried to make each individual commit a logical unit to make reviewing (and cherry picking/reverting) easier.

To do a local tox run do the following in your development virtualenv:

    pip install -U tox
    tox

After a successful tox run (this is assuming you have py27, py34 and py35 available on your dev machine) a coverage report should be available by opening `./htmlcov/index.html` in your favourite browser.

(ref #144)

### CODE REVIEW

**Comment by alsoicode** [comment]
@jaap3 Wow. Thank you very much for the great additions and fixes. I'd like to update the readme with information pertinent to compatibility with Django versions. I've tried to keep this project as backwards compatible as possible.

Would you mind taking a look at the readme and making any updates as needed?

**Comment by jaap3** [comment]
I had a look at updating the readme. I then started wondering which file should be updated. There's a  RST file and a MD file (both seem to pretty much contain the same content). Then there's setup.py which sources its long_description from a third file called README, (without an extension) which is not in the repository. Am I missing something? Should I just update both files simultaneously?

**Comment by alsoicode** [comment]
I edit the Markdown file, then generate the .rst from that using pandoc. The setup.py referencing just `README` is a terrible, glaring oversight. It should be updated to reference `README.rst`

**Comment by alsoicode** [comment]
@jaap3 I've updated setup.py to point to README.rst.

**Comment by alsoicode** [comment]
@jaap3 I'd like to get this PR merged, but also don't want to cause issues with backwards compatibility. These changes look like they'll work only if you're using Django 1.10 or higher, is that correct?

**Comment by jaap3** [comment]
No, with these changes django-admin-sortable remains compatible with Django 1.8, 1.9, 1.10 and probably 1.11 as well. Running tox with the config I've added runs the test suite against these Django versions with Python 2.7, 3.4 and 3.5. The last time I've tried everything passed. I've also manually ran the demo project with 1.8 and everything looks good. 

btw, It would be nice if the https://travis-ci.org/iambrandontaylor/django-admin-sortable/ project was reactivated for this project.

I haven't yet found the time to update the README.

**Comment by alsoicode** [comment]
I've contacted Travis about the repo being inactive. I'm not sure why that happened.

**Comment by alsoicode** [comment]
I'm going for broke, and will release this as 2.1 :)

**Comment by alsoicode** [comment]
@jaap3 Version 2.1.0 has been released to PyPi. Thank you so much for the improvements.

**Pull request merged**
