### PR TITLE
add polish translation

### PR DESCRIPTION
**Pull request by TomaszGabrysiak**
Added missing Polish translation.

### CODE REVIEW

**Comment by alsoicode** [comment]
Thank you very much for taking the time to do that. I'll get this worked in a deployed out to PyPi.

**Comment by alsoicode** [comment]
@TomaszGabrysiak version 1.8.2 has been deployed to PyPi

**Comment by TomaszGabrysiak** [comment]
@alsoicode nice, thanks!

**Comment by alsoicode** [comment]
You're very welcome.

**Pull request merged**
