### PR TITLE
Use only one README

### PR DESCRIPTION
**Pull request by adamchainz**
I can't work out why the README was being maintained in both markdown and reStructuredText, so I've removed the markdown version. Also setup.py seemed broken to me as it referred to the non-existent README file, so I've pointed it at README.rst.

### CODE REVIEW

**Comment by alsoicode** [comment]
The reStructuredText version is for PyPi. The Markdown version is for Github. So they're both needed. The README in setup.py is an oversight, so if you want to point that to the .rst file and only have that change in the pull request, I'll merge that.

**Comment by adamchainz** [comment]
Github supports rST you know?

**Comment by alsoicode** [comment]
That's fine, but I still prefer to use the Markdown version for Github. Creating the .rst is easy via Pandoc, so I never make changes to both files by hand.

**Comment by adamchainz** [comment]
I don't see the point of doing that extra work. rST can actually render better because it has more syntax.

**Comment by alsoicode** [comment]
I've updated the setup.py to point to the .rst version. Closing.

**Comment by alsoicode** [comment]
@adamchainz Please understand I'm not trying to be rude or anything, I just prefer using the Markdown syntax, and don't mind running the Pandoc command to generate the file. Even if rst does have better formatting, it's just my preference :)

**Pull request closed without merging**
