### PR TITLE
fix sortable function not found

### PR DESCRIPTION
**Pull request by flyingeek**
Adminsortable uses django.jQuery

I had the problem when adding another jQuery, since all adminsortable  scripts are using django.jQuery, I think it is safe to do the same here, it solves my problem anyway.

### CODE REVIEW

**Comment by alsoicode** [comment]
Hi. What version of adminsortable and Django are you using to produce this issue?

**Comment by flyingeek** [comment]
Django 1.6 and admin-sortable 1.8

**Comment by alsoicode** [comment]
ok, let me do some testing and if all is well, I'll get this merged.

**Comment by alsoicode** [comment]
Ok, I have released 1.8.1 to PyPi. Thanks for the addition!

**Comment by flyingeek** [comment]
Wow that was super quick!

**Comment by alsoicode** [comment]
Thanks. I try :)

**Pull request merged**
